// sort.mjs — single source of truth for the explorer's column sorting.
//
// One audience each way, one function:
//   - site/explorer.js sorts rows with it (loaded as the generated
//     site/shared-sort.js, which serialises nameCmp / comparator the same way
//     shared-rules.js serialises recScore).
//   - scripts/explorer.test.mjs executes the same serialised bundle, so the
//     comparator's behaviour is pinned against drift from the source.
//
// Keep the comparator here, never inline in explorer.js: the browser repaint
// and the regression tests must run the exact same code (same contract as
// rows.mjs / shared-rows.js).
//
// Provider fields come from providers.json, which community PRs can edit —
// treat every field as untrusted: comparisons must never throw on null,
// missing keys, or non-numeric values.

export const nameCmp = (a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0);

/**
 * The explorer's row comparator. `sortKey` is the th data-key, `sortDir` is
 * 1 for ascending, -1 for descending. Two columns map onto a more useful
 * criterion than their raw field:
 *   - 'verified' sorts by last_verified (YYYY-MM-DD), not the boolean, with
 *     rows that have no date always sinking to the bottom.
 *   - 'free_tier' sorts by the free_type taxonomy (permanent tiers first,
 *     one-time trial credits last), since the free_tier text is free-form
 *     prose and alphabetising it is noise.
 * Every other column sorts by its raw value, with a deterministic name
 * tiebreak for 'recommended' and the two mapped columns.
 */
export function comparator(sortKey, sortDir, a, b) {
  if (sortKey === 'recommended') { const d = recScore(b) - recScore(a); return d !== 0 ? d : nameCmp(a, b); }
  if (sortKey === 'verified') {
    // Sort by last_verified, not the boolean: every verified row would
    // compare equal. Rows without a date always sink to the bottom.
    const vd = (p) => (p.last_verified ? Date.parse(p.last_verified + 'T00:00:00Z') : null);
    const aU = vd(a) === null, bU = vd(b) === null;
    if (aU !== bU) return aU ? 1 : -1;
    if (aU) return nameCmp(a, b);
    const d = vd(a) - vd(b) || nameCmp(a, b);
    return sortDir === 1 ? d : -d;
  }
  if (sortKey === 'free_tier') {
    // "What's free" is free-form prose — alphabetising it is noise. Sort by
    // the free_type taxonomy instead: permanently-free models first, one-time
    // trial credits last, with the name as a stable tiebreak.
    const rank = { perpetual: 0, 'renewing-quota': 1, 'recurring-credit': 2, 'trial-credit': 3 };
    const rk = (p) => (rank[p.free_type] ?? 4);
    const d = rk(a) - rk(b) || nameCmp(a, b);
    return sortDir === 1 ? d : -d;
  }
  let av = a[sortKey], bv = b[sortKey];
  if (typeof av === 'boolean') { av = av ? 1 : 0; bv = bv ? 1 : 0; }
  av = (av ?? ''); bv = (bv ?? '');
  return av < bv ? -sortDir : av > bv ? sortDir : 0;
}

/**
 * The exact client bundle the browser runs (written to site/shared-sort.js by
 * build.mjs). Serialising here — next to the code it ships — means build.mjs
 * and explorer.test.mjs both consume the same string: the build writes it,
 * the test executes it, and neither can drift from the module.
 */
export function clientBundle() {
  return `// AUTO-GENERATED by scripts/build.mjs from scripts/lib/sort.mjs — do not edit.
window.FLLM_SORT = (function () {
  const { recScore } = window.FLLM_RULES;
  const nameCmp = ${nameCmp.toString()};
  const comparator = ${comparator.toString()};
  return { comparator };
})();
`;
}

// recScore is referenced by name inside comparator so the serialised copy can
// pick it up from window.FLLM_RULES; importing it here keeps the same name in
// scope for the server-side module consumers.
import { recScore } from './rules.mjs';
